### PR TITLE
Adding slack package for basic info/critical messaging

### PR DESCRIPTION
**Pull request by pa3ng**

### CODE REVIEW

**Comment by adamdecaf** [comment]
Why does this need to be in moov-io/base?

**Comment by pa3ng** [comment]
Hey @adamdecaf, me and @darwinz noticed we were duplicating slack messaging implementations in a couple of our services. We thought we could probably move the shared logic in the base package. What are your thoughts?

**Comment by adamdecaf** [comment]
I've been trying to keep moov-io/base pretty minimal and contain packages which *all* Moov projects use. If we wanted to make a more specific package we could follow the route of https://github.com/moov-io/go-sftp. 

That said this package looks to be one file and ~2 constants so I think copying the code makes more sense than a shared package. 

From the [Go Proverbs](https://go-proverbs.github.io/), "A little copying is better than a little dependency."

**Comment by pa3ng** [comment]
Thanks for your input @adamdecaf. That makes sense to me; I'm cool w/ copypasta for now until we see more projects needing it, since it's only a couple of projects atm 👍🏼

**Pull request closed without merging**
